SFO-12: navbar, page content, footer, form and make page respon…
frank-martinez-iest/exercise-2 pull request #6
Opened 2020-12-16 01:45 UTC by nanyssalazar

This is how it looks like: 
<img width="1552" alt="Screen Shot 2020-12-15 at 19 44 18" src="https://user-images.githubusercontent.com/55749067/102294038-fb68b480-3f0d-11eb-931e-205ff04323a5.png">
<img width="1552" alt="Screen Shot 2020-12-15 at 19 44 28" src="https://user-images.githubusercontent.com/55749067/102294046-002d6880-3f0e-11eb-84c1-c9fb26ba3f48.png">

2020-12-16 01:49 UTC, nanyssalazar commented
Forgot to tell that the form is accessed by clicking on the **user** img (next to the "Create a Sketch" btn) in the navbar and then **Join openProcessing**
<img width="1532" alt="Screen Shot 2020-12-15 at 19 48 05" src="https://user-images.githubusercontent.com/55749067/102294246-7e8a0a80-3f0e-11eb-8e8b-db530b46d99f.png">
<img width="1532" alt="Screen Shot 2020-12-15 at 19 48 10" src="https://user-images.githubusercontent.com/55749067/102294250-7fbb3780-3f0e-11eb-9a00-749981ae6345.png">

2020-12-18 01:53 UTC, frank-martinez-iest commented on Andrea/form.html
> + <header>
I think this element must be inside the body. Also, I don't see where are we closing the tag?

2020-12-18 01:54 UTC, frank-martinez-iest commented on Andrea/form.html
> +        <label class="form-fields" for="">name</label>
Add the id of the input it belongs to inside the for attribute

2020-12-18 01:55 UTC, frank-martinez-iest commented on Andrea/form.html
> +        <input type="text">
Add an ID that makes sense with its label

2020-12-18 01:55 UTC, frank-martinez-iest commented on Andrea/form.html
> +        <input type="text" name="" id="">
same as above

2020-12-18 01:55 UTC, frank-martinez-iest commented on Andrea/form.html
> +        <input type="password" name="" id="">
same as above

2020-12-18 01:55 UTC, frank-martinez-iest commented on Andrea/form.html
> +        <button class="form-btn">Join</button>
button type?

2020-12-18 01:56 UTC, frank-martinez-iest commented on Andrea/index.html
> +                    <input type="text" placeholder="Search">
This input needs a label that is hidden, so that we still have accessibility in mind

2020-12-18 04:01 UTC, frank-martinez-iest commented on Andrea/index.html
> +                        <button class="user-btn" type="submit" onclick="location.href='form.html';" >Join openProcessing</button>
To redirect a user to another page the semantic element is the anchor `<a>`. You can style the anchor so it looks as a button or anything else you need

2020-12-18 04:02 UTC, frank-martinez-iest commented on Andrea/index.html
> +                <button type="submit" class="hero-btn btn-outline">join</button>
same as above, by the text I infer this is a redirect and needs to be in an anchor

2020-12-18 04:02 UTC, frank-martinez-iest commented on Andrea/index.html
> +                <button class="hero-btn">Sign in</button>
same as above

2020-12-18 04:05 UTC, frank-martinez-iest commented on Andrea/index.html
> +            <div class="features-articles">
This tag element is not an article nor it works as an article, so is confusing. Could you rename it? Maybe `class="features__feature"`? This way Im establishing this is one of many features that are listed inside the class `"features"`

2020-12-18 04:06 UTC, frank-martinez-iest commented on Andrea/index.html
> +                <h2 class="features-title">Connect and inspire</h2>
`class="features__feature-*"`

2020-12-18 04:09 UTC, frank-martinez-iest commented on Andrea/index.html
> +            <!-- Should I use a div here? -->
is this comment still relevant?

2020-12-18 04:10 UTC, frank-martinez-iest commented on Andrea/index.html
> +            <h2 class="sketches-title">Sketches that are <span><img class="heart-img" src="img/heart-arrow.png" alt="heart with arrow"> this week</span></h2>
Here you can do `class="sketches__title`

2020-12-18 04:10 UTC, frank-martinez-iest commented on Andrea/index.html
> +            <div>
I think this div is no longer needed

2020-12-18 04:11 UTC, frank-martinez-iest commented on Andrea/index.html
> +            <div>
lets use section here instead of a div

2020-12-18 04:11 UTC, frank-martinez-iest commented on Andrea/index.html
> +            <div>
same as above

2020-12-18 04:11 UTC, frank-martinez-iest commented on Andrea/index.html
> +            <div>
same as above

2020-12-18 04:11 UTC, frank-martinez-iest commented on Andrea/index.html
> +            <div>
same as above

2020-12-18 04:12 UTC, frank-martinez-iest commented on Andrea/javascript.js
> +  if (x.style.display === "none") {
This is a good js exercise, but can you check how to do an element toggle using css only? There is a way...

2020-12-18 04:12 UTC, frank-martinez-iest requested changes
Good job, the design looks very similar to the origina! 👏 . Left few comments

2020-12-18 05:25 UTC, nanyssalazar commented on Andrea/index.html
> +                <h2 class="features-title">Connect and inspire</h2>
would this be `class="features__feature--title"`? @frank-martinez-iest

2020-12-18 19:58 UTC, nanyssalazar commented on Andrea/index.html
> +                    <button type="submit">Create a Sketch</button>
@frank-martinez-iest like you said in the comment above, would this also be an `<a>` since it will redirect the user to another page?

2020-12-19 22:22 UTC, merged