EXERCISE 2 FIRST ATTEMPT
frank-martinez-iest/exercise-2 pull request #7
Opened 2020-12-16 02:14 UTC by josh231101

== FEATURES ==
* Sidebar (Sidebar is not yet finished but it's included)
* Navbar
* Hero section with animation using grid
* Main content
* 1- Grid beautiful cards 
* 2.- How it works section with 4 cards
* 3.- Mobile experience with iphone mockup
* 4.- Coupon section with a video slightly overlapped
* Footer 
Images:
![image](https://user-images.githubusercontent.com/47585614/102295461-fbb67f00-3f10-11eb-9f75-4c2819ca7ae0.png)
![image](https://user-images.githubusercontent.com/47585614/102295485-0709aa80-3f11-11eb-85c2-8bd9aa0cf141.png)
![image](https://user-images.githubusercontent.com/47585614/102295506-1557c680-3f11-11eb-925d-487acc420db4.png)
![image](https://user-images.githubusercontent.com/47585614/102295522-20125b80-3f11-11eb-91e5-76d1359e2c8b.png)
![image](https://user-images.githubusercontent.com/47585614/102295560-34eeef00-3f11-11eb-9270-2263a57e7c5a.png)
![image](https://user-images.githubusercontent.com/47585614/102295588-4b954600-3f11-11eb-9462-230360bead0b.png)

2020-12-16 03:29 UTC, josh231101 commented on Josue/index.html
> +            <input
I was following the design, UI designer forgot accessibility design

2020-12-18 01:36 UTC, frank-martinez-iest commented on Josue/css/styles.css
> +  padding: 16px 52px;
preferably keep px's to be a factor of 8 (48px or 56px) so we can have consistency

2020-12-18 01:37 UTC, frank-martinez-iest commented on Josue/css/styles.css
> +  transition: all 400ms ease-out;
💯

2020-12-18 01:38 UTC, frank-martinez-iest commented on Josue/css/styles.css
> +.sidebar--open {
You mastered BEM!! 🤟

2020-12-18 01:41 UTC, frank-martinez-iest commented on Josue/css/styles.css
> +  margin: 0 8px;
NIT: If you set the horizontal margin to 16px looks better, don't you think? 
![image](https://user-images.githubusercontent.com/71283270/102563823-0565f100-408f-11eb-8dab-1018e033f281.png)

2020-12-18 01:42 UTC, frank-martinez-iest commented on Josue/css/styles.css
> +/* HOW IT WORKS SECTION*/
I loved the comments, very useful

2020-12-18 01:44 UTC, frank-martinez-iest commented on Josue/css/styles.css
> +.coupon-section {
NIT: I would prefer this class to be called coupon or coupon-container, not sure I've seen the word `section` being used as it seems redundant or vague.

2020-12-18 01:46 UTC, frank-martinez-iest commented on Josue/js/app.js
> +const openSideBar = () => {
This is a good JS exercise, but there is a CSS only way to achieve this, have you seen it?

2020-12-18 01:46 UTC, frank-martinez-iest commented on Josue/index.html
> +        arialabel=""
I think this is not needed

2020-12-18 01:49 UTC, frank-martinez-iest commented on Josue/index.html
> +      <section class="section-container download-section">
lets try to come up with a better name for this element, it is a section but the classname is `section-container` which is redundant

2020-12-18 01:49 UTC, frank-martinez-iest commented on Josue/index.html
> +      <section class="section-container coupon-section">
same as above

2020-12-18 01:51 UTC, frank-martinez-iest requested changes
So much progress in such short time! Im proud of you, great job! Just left a couple comments here and there

2020-12-18 01:51 UTC, frank-martinez-iest commented on Josue/index.html
> +          <p class="wh">
same as above, wh is not clear what it means

2020-12-18 01:51 UTC, frank-martinez-iest commented on Josue/index.html
> +          <hr class="hr--green" />
we probably could have gotten away with css to not need an HR to see a line here but lets keep it like this

2020-12-18 19:25 UTC, josh231101 commented on Josue/css/styles.css
> +  margin: 0 8px;
Yup even better

2020-12-18 19:30 UTC, josh231101 commented on Josue/css/styles.css
> +.coupon-section {
I saw it here: https://zova.com/
But indeed it's redundant, gonna change it

2020-12-18 19:38 UTC, josh231101 commented on Josue/index.html
> +          <hr class="hr--green" />
border-bottom, I thought of it but the green line according to the design wasn't taking the width of the text

2020-12-18 19:48 UTC, josh231101 commented on Josue/index.html
> +      <section class="section-container download-section">
Doubt: Should I change the name of section-container or download-section? Or both :laughing: ??
The section-container is css code is:
`.section-container {
  box-sizing: border-box;
  width: 100%;
  padding: 80px;
  margin-left: auto;
  margin-right: auto;
}`
Should I call the section something like -> container-wrapper??

2020-12-18 20:12 UTC, josh231101 commented on Josue/js/app.js
> +const openSideBar = () => {
I saw some codepen projects, many of them with sass or less, and the ones with pure css use the burger icon as an input type checkbox so when is active they add some CSS, should I do that or leave it with JS?

2020-12-19 04:08 UTC, josh231101 commented on Josue/index.html
> +          class="video-section__content"
container__video-content

2020-12-19 22:22 UTC, merged